export const ALLOWED_TAGS = {
  a: 'a',
  article: 'article',
  b: 'b',
  br: 'br',
  button: 'button',
  div: 'div',
  em: 'em',
  footer: 'div',
  header: 'div',
  hr: 'hr',
  h1: 'h1',
  h2: 'h2',
  h3: 'h3',
  h4: 'h4',
  h5: 'h6',
  h6: 'h6',
  i: 'i',
  img: 'img',
  li: 'li',
  nav: 'div',
  p: 'p',
  pre: 'pre',
  section: 'section',
  span: 'span',
  style: 'style',
  strong: 'strong',
  table: 'table',
  tbody: 'tbody',
  td: 'td',
  thead: 'thead',
  tfoot: 'tfoot',
  tr: 'tr',
  u: 'u',
  ul: 'ul',
} as const;

export const ALLOWED_TAGS_VALUES = Object.values(ALLOWED_TAGS);
