name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm@8.15.5

      - name: Install dependencies and build
        run: pnpm i --frozen-lockfile

      - name: Run linter
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Run build
        run: pnpm build:lib

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore(release): version package 🦋"
          publish: pnpm run publish:package
          version: pnpm run version:package
          commit: "chore(release): version package 🦋"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build demo version
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          pnpm build:demo
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H react-web-builder.100bit.pl >> ~/.ssh/known_hosts
          rsync -avz --delete ./storybook-static/ debian@react-web-builder.100bit.pl:/var/www/html/react-web-builder.100bit.pl/
